version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "9000"
  
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"  # Expose port 80 to the outside
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web